### ISSUE TITLE
learn deploying of django project into azure

### ISSUE THREAD

**Issue by Omarelsherif010** [DevMed22/Summer-training-22#13]
https://docs.microsoft.com/en-us/training/modules/django-deployment/

**Comment by tabana1** [comment]
https://www.youtube.com/watch?v=D6Wyk9q2JM0&t=12s

**Comment by Omarelsherif010** [comment]
Looks good, we will discuss it today in our meeting.
Good Job @tabana1

**Comment by tabana1** [comment]
thanks

**Comment by Omarelsherif010** [comment]
App deployed successfully into Azure but there is a problem with reading the content because of administration rights
