### ISSUE TITLE
hosting our website for free on Azure or DigitalOcean

### ISSUE THREAD

**Issue by Omarelsherif010** [DevMed22/Summer-training-22#5]
I suggest hosting our website on a cloud hosting provider to learn the process of getting the domain, configuring the server with linux image, uploading files, and making our website public.
<br>
Watch this tutorial to guide us in doing this step: 
[Hosting a Django website on DigitalOcean](https://www.youtube.com/watch?v=COX-1dopn14)

**Comment by tabana1** [comment]
we need money to register in  Digital Ocean

**Comment by tabana1** [comment]
i suggest we use [azure for student ]( https://azure.microsoft.com/en-us/free/students/)
and [we deploy our project according to ](https://www.youtube.com/watch?v=D6Wyk9q2JM0&t=12s)

- add azure tools extension on vs code 
- add white noise dependency
