### ISSUE TITLE
getting free domain and host for students

### ISSUE THREAD

**Issue by Omarelsherif010** [DevMed22/Summer-training-22#9]
Hi @esmael889  
Can you get more detail on how to get a free domain and hosting using [GitHub Student Developer Pack](https://education.github.com/pack#)

**Comment by esmael889** [comment]
Hi @Omarelsherif010  ok I will read more detail about that and try to do it.

**Comment by esmael889** [comment]
you need to sign in with a college email into [GitHub student  developer pack ](https://education.github.com/pack?sort=popularity&tag=Cloud) wait to receive and accept  then get your domain from one of three options:
Namecheap
Name.com
.Tech domain.
and for the cloud, we can use Digitalocean or Microsoft azure
I think Microsoft azure will be the best option.
